[theme]
base="dark"
primaryColor="#38BDF8"
backgroundColor="#030712"
secondaryBackgroundColor="#0B0F19"
textColor="#F8FAFC"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
